### ISSUE TITLE
Improve Pantheon Experience for Larger Organizations using Custom Upstreams

### ISSUE THREAD

**Issue by kreynen** [backdrop-ops/backdrop-pantheon#19]
When we get to the point we have a basic Backdrop install that is near feature parity with our D7 install profile, we'll invest a few weeks to update our devops and server configuration to support both D7 and Backdrop.  Until then we are using Pantheon to host our Backdrop sites.  We've created https://github.com/CuBoulder/backdrop-pantheon to maintain all sites using a custom upstream similar to how we maintain https://github.com/CuBoulder/cu-express-drops-7 and https://github.com/CuBoulder/cu-express-drops-8.

We haven't written an install profile for Backdrop yet, but we'll port https://www.drupal.org/project/profile_switcher to convert existing sites after we do.

![screen shot 2018-08-15 at 8 46 57 am](https://user-images.githubusercontent.com/385234/44154595-50f08c1c-a068-11e8-9c78-21ddd0676a75.png)

These all have PRs (or will shortly) and seem like big wins for the average user who tries backdrop.

- [x] https://github.com/backdrop-ops/backdrop-pantheon/issues/10 - Files directory not writable
- [x] https://github.com/backdrop-ops/backdrop-pantheon/issues/17 - Port pantheon_api
- [x] https://github.com/backdrop-ops/backdrop-pantheon/issues/9 - Set PHP to version 7
- [ ] ~~https://github.com/backdrop-ops/backdrop-pantheon/issues/18 - Add support for standardized location of settings.local.php on Pantheon~~

It looks like the Drush compatibility referenced in https://github.com/backdrop-ops/backdrop-pantheon/issues/6 still needs work.  Unfortunately, I'm not that familiar using Drush with Backdrop  nor how Pantheon allows the customization of Drush on their platform... yet.  That is still going to require some work.

The rest of these issues just need someone with the proper permissions to move them forward.

**Comment by kreynen** [comment]
Once we get the Drush issues figured out, it should be smooth sailing for the next large org that wants to build a custom upstream.
